name: Lint web e2e
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  lint-web-e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web-e2e
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Cache saved yarn cache directory
        uses: actions/cache@v2
        with:
          path: apps/web-e2e/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('apps/web-e2e/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn zx ./scripts/lint.mjs
