name: Lint web
on: [ pull_request ]
jobs:
  app-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/web
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

#      - name: Cache yarn
#        id: cache-yarn
#        uses: actions/cache@v2
#        with:
#          path: 'node_modules'
#          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: ./scripts/lint.mjs
