name: Test everything
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  install-web:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install web
        uses: ./.github/actions/install-web

      - name: Lint
        run: yarn zx ./scripts/lint.mjs
        working-directory: apps/web

#  install-web-e2e:
#    runs-on: ubuntu-latest
#    needs: setup
#    steps:
#      - name: Cache saved yarn cache directory
#        uses: actions/cache@v2
#        with:
#          path: apps/web-e2e/.yarn
#          key: ${{ runner.os }}-yarn-${{ hashFiles('apps/web-e2e/yarn.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-yarn-
#
#      - name: Install dependencies
#        run: yarn --frozen-lockfile
#        working-directory: apps/web-e2e

#  lint-web:
#    runs-on: ubuntu-latest
#    needs: install-web
#    steps:
#      - name: Lint
#        run: yarn zx ./scripts/lint.mjs
#        working-directory: apps/web

#  lint-web-e2e:
#    runs-on: ubuntu-latest
#    needs: install-web-e2e
#    steps:
#      - name: Lint
#        run: yarn zx ./scripts/lint.mjs
#        working-directory: apps/web-e2e
