name: Test everything
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  install-web:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install web
        uses: ./.github/actions/install-web

  install-web-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install web
        uses: ./.github/actions/install-web-e2e

  lint-web:
    runs-on: ubuntu-latest
    needs: install-web
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install web
        uses: ./.github/actions/install-web

      - name: Lint
        run: yarn zx ./scripts/lint.mjs
        working-directory: apps/web

  lint-web-e2e:
    runs-on: ubuntu-latest
    needs: install-web-e2e
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install web
        uses: ./.github/actions/install-web

      - name: Lint
        run: yarn zx ./scripts/lint.mjs
        working-directory: apps/web
